In [5]:
import pandas as pd
from pandas import Series, DataFrame

In [6]:
a = pd.read_csv("csv.txt", delimiter=" ")
a

가구 월평균가구소득(천원)  가구당자동차보유대수  가구당일일통행량
0    1       4,000           0         2
1    2       6,000           0         4
2    3      17,000           2        10
3    4      11,000           0         5
4    5       4,500           1         5
5    6      17,000           3        15
6    7       9,500           1         7
7    8       9,000           0         4
8    9       7,000           1         6
9   10      19,000           3        13
10  11      18,000           1         8
11  12      21,000           1         9
12  13       7,000           2         9
13  14      11,000           2         6
14  15      11,000           2         7
15  16      13,000           2        11
16  17      15,000           2        12
17  18      11,000           1         8
18  19      13,000           1         8
19  20      15,000           1         9

In [7]:
a.ix[:, 1] = a[a.columns[1]].apply(lambda x: x.replace(",", "")).astype(int)

In [8]:
a

가구  월평균가구소득(천원)  가구당자동차보유대수  가구당일일통행량
0    1         4000           0         2
1    2         6000           0         4
2    3        17000           2        10
3    4        11000           0         5
4    5         4500           1         5
5    6        17000           3        15
6    7         9500           1         7
7    8         9000           0         4
8    9         7000           1         6
9   10        19000           3        13
10  11        18000           1         8
11  12        21000           1         9
12  13         7000           2         9
13  14        11000           2         6
14  15        11000           2         7
15  16        13000           2        11
16  17        15000           2        12
17  18        11000           1         8
18  19        13000           1         8
19  20        15000           1         9

In [9]:
a.mean()

가구                10.5
월평균가구소득(천원)    11950.0
가구당자동차보유대수         1.3
가구당일일통행량           7.9
dtype: float64

In [10]:
b = a[a.ix[:, 1] > 10000]
b

가구  월평균가구소득(천원)  가구당자동차보유대수  가구당일일통행량
2    3        17000           2        10
3    4        11000           0         5
5    6        17000           3        15
9   10        19000           3        13
10  11        18000           1         8
11  12        21000           1         9
13  14        11000           2         6
14  15        11000           2         7
15  16        13000           2        11
16  17        15000           2        12
17  18        11000           1         8
18  19        13000           1         8
19  20        15000           1         9

In [11]:
b[b.ix[:, 1] > 15000].mean()

가구                 8.4
월평균가구소득(천원)    18400.0
가구당자동차보유대수         2.0
가구당일일통행량          11.0
dtype: float64

In [12]:
import numpy as np
x = np.array([7.9, 7.9, 7.9])
y = np.array(list(reversed([-2.62, 0.35, 3.1])))
z = np.array(list(reversed([2.475, -0.4, -4.15])))
x, y, z

(array([ 7.9,  7.9,  7.9]),
 array([ 3.1 ,  0.35, -2.62]),
 array([-4.15 , -0.4  ,  2.475]))

In [13]:
w = np.array([x + y[2] + z,
x + y[1] + z,
x + y[0] + z])
mca = w.T
mca

array([[  1.13 ,   4.1  ,   6.85 ],
       [  4.88 ,   7.85 ,  10.6  ],
       [  7.755,  10.725,  13.475]])

In [14]:
cca = np.array([
    [3.33, 5, 6.85],
    [6, 8.33, 8.5],
    [9, 9, 12.66]
])
cca

array([[  3.33,   5.  ,   6.85],
       [  6.  ,   8.33,   8.5 ],
       [  9.  ,   9.  ,  12.66]])

In [15]:
((mca - cca) ** 2).sum() / 9

1.8594083333333329

In [17]:
cca_df = DataFrame(cca, index=["0대", "1대", "2대 이상"],
                  columns=["1000만 이하", "1001만 ~ 1500만", "1500만 초과"])
cca_df.name = "CCA"
cca_df

1000만 이하  1001만 ~ 1500만  1500만 초과
0대         3.33           5.00      6.85
1대         6.00           8.33      8.50
2대 이상      9.00           9.00     12.66

In [18]:
mca_df = DataFrame(mca, index=["0대", "1대", "2대 이상"],
                  columns=["1000만 이하", "1001만 ~ 1500만", "1500만 초과"])
mca_df.name = "MCA"
mca_df

1000만 이하  1001만 ~ 1500만  1500만 초과
0대        1.130          4.100     6.850
1대        4.880          7.850    10.600
2대 이상     7.755         10.725    13.475

In [19]:
mca_df - cca_df

1000만 이하  1001만 ~ 1500만  1500만 초과
0대       -2.200         -0.900     0.000
1대       -1.120         -0.480     2.100
2대 이상    -1.245          1.725     0.815